### ISSUE TITLE
ld: Invalid value (Producer: 'LLVM13.0.0-rust-1.59.0-nightly' Reader: 'LLVM APPLE_1_1300.0.29.3_0') for architecture arm64

### ISSUE THREAD

**Issue by simonpham** [isar/isar#178]
**Steps to Reproduce**
1. Update build architecture to arm64 & enable Build Active Architecture only
2. Run `flutter build ipa` or Create release Archive in Xcode

ld: Invalid value (Producer: 'LLVM13.0.0-rust-1.59.0-nightly' Reader: 'LLVM APPLE_1_1300.0.29.3_0') for architecture arm64

**Code sample**
```
isar example project
```

**Version**
 - Platform: iOS arm64
 - Flutter version: 2.8.1
 - Isar version: 1.0.5
 - Isar Generator version: 1.0.5

**Comment by simonpham** [comment]
This can be useful :)
https://stackoverflow.com/questions/52924569/how-can-i-compile-a-rust-program-with-a-custom-llc/56399256#56399256

**Comment by leisim** [comment]
@simonpham Thanks for the report and link! Which version of XCode do you use?

**Comment by leisim** [comment]
Fixed in `2.0.0-dev.0`

**Comment by andj207** [comment]
@leisim after I updated the new version `2.0.0-dev.0`, the build process throws errors below:

     Error: Couldn't find constructor 'FilterGroup'.
    ../…/src/isar_connect_base.dart:122
          filter: FilterGroup(filters: [filter], type: FilterGroupType.or),
                  ^^^^^^^^^^^
    : Error: Couldn't find constructor 'FilterGroup'.
    ../…/src/isar_connect_base.dart:157
          return FilterGroup(
                 ^^^^^^^^^^^
    : Error: Method not found: 'FilterNot'.
    ../…/src/isar_connect_base.dart:163
          return FilterNot(
                 ^^^^^^^^^
I have tried to `flutter clean` and `flutter pub get` but the errors are still there.

**Comment by Allenxuxu** [comment]
https://github.com/isar/isar/issues/303 
This seems to be a similar problem

**Comment by jtmuller5** [comment]
I am still getting this error with isar 2.5.0 trying to archive for iOS arm64. The app runs fine in debug mode but won't archive.

All Android builds works fine as well.

`Invalid value (Producer: 'LLVM14.0.1-rust-1.62.0-nightly' Reader: 'LLVM APPLE_1_1300.0.29.30_0') for architecture arm64`

**Comment by robotoss** [comment]
The problem is relevant to 3.0.0-dev.0

**Comment by leisim** [comment]
@robotoss Which XCode version do you use?

**Comment by robotoss** [comment]
@leisim Xcode - 13.2.1

I resolved problem change in Pods ->  Enable Bitcode to NO

<img width="1249" alt="Screen Shot 2022-05-18 at 14 13 16" src="https://user-images.githubusercontent.com/34773197/169026160-183bd789-6112-4b34-bcc2-de00de45f602.png">
