### ISSUE TITLE
Could not initialize IsarCore library in physical device. But in Emulator initialize

### ISSUE THREAD

**Issue by catalunha** [isar/isar#619]
**Steps to Reproduce**
this is the error
![image](https://user-images.githubusercontent.com/19995819/188135332-d0b78e52-3e94-41bb-bf3f-d4bd8b6c298a.png)
When I run this code on the physical device Samsung J5
```
import 'dart:io';
import 'package:isar/isar.dart';
import 'package:noctua_isar/app/domain/models/contact_model.dart';
import 'package:path_provider/path_provider.dart';
  void openIsarInstance() async {
    Directory tempDir = await getTemporaryDirectory();
    String tempPath = tempDir.path;
    // I/flutter (26634): tempPath: /data/user/0/org.brintec.noctua_isar.noctua_isar/cache

    Directory appDocDir = await getApplicationDocumentsDirectory();
    String appDocPath = appDocDir.path;
    // I/flutter (26634): appDocPath: /data/user/0/org.brintec.noctua_isar.noctua_isar/app_flutter

    print('tempPath: $tempPath');
    print('appDocPath: $appDocPath');
    final isar = await Isar.open(
      schemas: [ContactModelSchema],
      directory: appDocPath,
    );
    final contact = ContactModel()..name = "name1";
    await isar.writeTxn((isar) async {
      contact.id = await isar.contactModels.put(contact);
    });
    final allContacts = await isar.contactModels.where().findAll();
    print(allContacts.toString());
  }
```
But when I run the same code on Pixel 2 Emulated by PopOS 22.04 it doesn't generate any error.

**Version**
 - Platform: Android  physical device Samsung J5 and Emulator by Pixel 2 API 31
 - Flutter version: 3.0.5
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Comment by leisim** [comment]
This has been fixed in the 3.0 versions 🙂

**Comment by catalunha** [comment]
```
name: noctua_isar
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Localizations
  flutter_localizations:
    sdk: flutter    
  intl: ^0.17.0
  # Gerenciador de estados
  get: ^4.6.5
  # Remote DataBase Back4app
  parse_server_sdk_flutter: ^3.1.3
  # Local DataBase Isar
  isar: ^2.5.0
  isar_flutter_libs: ^2.5.0
  # Google
  google_fonts: ^3.0.1  
  # upload Files
  image_picker: ^0.8.5
  image_picker_for_web: ^2.1.8
  # file_picker: ^5.0.1
  # path_provider
  path_provider: ^2.0.11
  # flutter.dev
  url_launcher: ^6.1.5
  # outros
  validatorless: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^2.5.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
```

**Comment by catalunha** [comment]
Thank you Leisim.
Then configure to ?
  isar: ^3.0.0
  isar_flutter_libs: ^3.0.0
  isar_generator: ^3.0.0

**Comment by catalunha** [comment]
modified to
```
  # Local DataBase Isar
  isar: ^3.0.0-dev.13
  isar_flutter_libs: ^3.0.0-dev.13
```
But still the error persists.
![image](https://user-images.githubusercontent.com/19995819/188138807-9dd140c3-72dd-46ea-9729-226a69ddb789.png)

**Comment by catalunha** [comment]
The complete error is
![image](https://user-images.githubusercontent.com/19995819/188139492-c3def301-8cf6-485e-b316-2cf980bf7b61.png)

**Comment by leisim** [comment]
Please do a flutter clean and pub upgrade and make sure that the latest version is used in your pubspec.lock file.

**Comment by leisim** [comment]
Remove the local database you have on the device and you are good to go

**Comment by catalunha** [comment]
Success. It worked on the Physical Device and emulator.
Now.
I uninstalled the android app. But how to remove all local database with Isar ?
And all Isar 2.5.0 documentation is compatible with this version ^3.0.0-dev.13

**Comment by leisim** [comment]
Your last issue is actually an Isar bug in the latest version. I'm releasing a fix to it soon. Going to close this issue however because it is tracked already.
